"use strict";

function generateRandomPiece() {
  const pieces = {
    I: {
      blocks: [
        {
          color: "#2a9d8f",
          borderColor: "black",
          positionX: 4,
          positionY: 0,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#2a9d8f",
          borderColor: "black",
          positionX: 4,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: true,
        },
        {
          color: "#2a9d8f",
          borderColor: "black",
          positionX: 4,
          positionY: 2,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#2a9d8f",
          borderColor: "black",
          positionX: 4,
          positionY: 3,
          width: 1,
          height: 1,
          isCenter: false,
        },
      ],
    },
    O: {
      blocks: [
        {
          color: "#e76f51",
          borderColor: "black",
          positionX: 4,
          positionY: 0,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#e76f51",
          borderColor: "black",
          positionX: 5,
          positionY: 0,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#e76f51",
          borderColor: "black",
          positionX: 4,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#e76f51",
          borderColor: "black",
          positionX: 5,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: false,
        },
      ],
    },
    Z: {
      blocks: [
        {
          color: "#c89f9c",
          borderColor: "black",
          positionX: 3,
          positionY: 0,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#c89f9c",
          borderColor: "black",
          positionX: 4,
          positionY: 0,
          width: 1,
          height: 1,
          isCenter: true,
        },
        {
          color: "#c89f9c",
          borderColor: "black",
          positionX: 4,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#c89f9c",
          borderColor: "black",
          positionX: 5,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: false,
        },
      ],
    },
    S: {
      blocks: [
        {
          color: "#edede9",
          borderColor: "black",
          positionX: 5,
          positionY: 0,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#edede9",
          borderColor: "black",
          positionX: 4,
          positionY: 0,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#edede9",
          borderColor: "black",
          positionX: 4,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: true,
        },
        {
          color: "#edede9",
          borderColor: "black",
          positionX: 3,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: false,
        },
      ],
    },
    L: {
      blocks: [
        {
          color: "#588157",
          borderColor: "black",
          positionX: 5,
          positionY: 0,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#588157",
          borderColor: "black",
          positionX: 5,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: true,
        },
        {
          color: "#588157",
          borderColor: "black",
          positionX: 4,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#588157",
          borderColor: "black",
          positionX: 3,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: false,
        },
      ],
    },
    J: {
      blocks: [
        {
          color: "#757bc8",
          borderColor: "black",
          positionX: 3,
          positionY: 0,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#757bc8",
          borderColor: "black",
          positionX: 3,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: true,
        },
        {
          color: "#757bc8",
          borderColor: "black",
          positionX: 4,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#757bc8",
          borderColor: "black",
          positionX: 5,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: false,
        },
      ],
    },
    T: {
      blocks: [
        {
          color: "#ae2012",
          borderColor: "black",
          positionX: 4,
          positionY: 0,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#ae2012",
          borderColor: "black",
          positionX: 3,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: false,
        },
        {
          color: "#ae2012",
          borderColor: "black",
          positionX: 4,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: true,
        },
        {
          color: "#ae2012",
          borderColor: "black",
          positionX: 5,
          positionY: 1,
          width: 1,
          height: 1,
          isCenter: false,
        },
      ],
    },
  };
  const piecesTypes = ["I", "O", "S", "Z", "L", "J", "T"];
  const randomPieceIndex = Math.floor(Math.random() * piecesTypes.length);
  const randomPieceType = piecesTypes[randomPieceIndex];
  const piece = pieces[randomPieceType];
  if (piece) {
    return piece;
  }
}
